name: ecto_events
description: GeoSpatial imaging and events
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  image_picker:
  path_provider: ^0.4.1
  flutter:
    sdk: flutter
  video_player: ^0.5.2
  cupertino_icons: ^0.1.2
  camera: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
  - family: mdi
    fonts:
    - asset: fonts/materialdesignicons-webfont.ttf
